

USE operationCoop_db;
INSERT INTO tags(name)
VALUES
('Gamer'),('gaming'),('playstation'),('xbox'),('streamer'),('gta'),('pcgaming'),
('nintendo'),('pubg'),('callofduty'),('follow'),('gamingcommunity'),('gamerlife'),
('videogame'),('meme'),('bhfyp'),('instagamer'),('cod'),('instagaming'),('art'),
('geek'),('pubgmobile'),('anime'),('youtuber'),('funny'),('gameplay'),('cosplay'),
('nintendoswitch'),('esports'),('lol'),('destiny'),('freefire'),('gamersofinstagram'),
('gamerguy'),('online'),('love'),('pro');


USE game_db;
INSERT INTO tags (name)
VALUES
('foodie'),
('Cooking'),
('Animals'),
('Plants'),
('Vegan'),
('non-veg'),
('Art'),
('DIY'),
('Action'),
('Coder'),
('Dance'),
('Music'),
('acting'),
('traveling'),
('Gamer'),
('gaming'),
('ps'),
('game'),
('playstation'),
('games'),
('videogames'),
('xbox'),
('streamer'),
('gta'),
('pcgaming'),
('nintendo'),
('pubg'),
('callofduty'),
('follow'),
('gamingcommunity'),
('gamerlife'),
('videogame'),
('meme'),
('pcgamer'),
('like'),
('bhfyp'),
('instagamer'),
('cod'),
('instagaming'),
('art'),
('geek'),
('pubgmobile'),
('anime'),
('youtuber'),
('r'),
('funny'),
('gameplay'),
('cosplay'),
('nintendoswitch'),
('esports'),
('lol'),
('destiny'),
('freefire'),
('gamersofinstagram'),
('gamerguy'),
('online'),
('love'),
('leagueoflegends'),
('instagram'),
('csgo'),
('k'),
('minecraft'),
('instagood'),
('pro');

